name: Run deteKT

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  detekt_check:
    runs-on: ubuntu-20.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: detektAll

